frontend_label: tasks-frontend
frontend_api_url: "{{ api_url }}"
frontend_app_node: "{{ app_node }}"
frontend_namespace: frontend
frontend_image: galihhhp/react-frontend:1.4
frontend_environment: "{{ env_suffix }}"
