- name: Cleanup cluster resources
  hosts: all
  connection: local
  vars:
    k8s_state: absent
    base_namespaces:
      - frontend
      - backend
      - database
      - monitoring
      - ingress-nginx
  roles:
    - role: namespace
    - role: storage-classes
    - role: network-policies
    - role: cert-manager-issuer
    - role: ingress-nginx
