- name: Apply Dev ClusterIssuer
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'dev-issuer.yml.j2') }}"
  when: ansible_limit == "dev"

- name: Apply Production ClusterIssuer
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'prod-issuer.yml.j2') }}"
  when: ansible_limit == "prod"
