on:
  workflow_dispatch:
jobs:
  networking:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v4
      - id: "auth"
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY_PROD }}"
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: "${{ secrets.PROJECT_ID }}"
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
      - name: Write prod.tfvars
        run: echo "$PROD_TFVARS" > prod.tfvars
        env:
          PROD_TFVARS: ${{ secrets.PROD_TFVARS }}
        working-directory: terraform
      - name: Terraform Init
        run: terraform init -backend-config=backend-prod.hcl
        working-directory: terraform
      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=prod.tfvars -target=module.network
        working-directory: terraform

  iam_pre:
    runs-on: ubuntu-latest
    needs: networking
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v4
      - id: "auth"
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY_PROD }}"
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: "${{ secrets.PROJECT_ID }}"
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
      - name: Write prod.tfvars from secret
        run: echo "$PROD_TFVARS" > prod.tfvars
        env:
          PROD_TFVARS: ${{ secrets.PROD_TFVARS }}
        working-directory: terraform
      - name: Terraform Init
        run: terraform init -backend-config=backend-prod.hcl
        working-directory: terraform
      - name: Terraform Apply IAM
        run: terraform apply -auto-approve -var-file=prod.tfvars -var='enable_workload_identity=false' -target=module.iam
        working-directory: terraform
